LATEST = 801
BATCH_SIZE = 100
CREATE_COVER = False
INCLUDE_VIDEO = False
INCLUDE_DESCRIPTION = False
EXCLUDE_IMAGES = False
INCLUDE_DESCRIPTION_IMAGE = False
INCLUDE_DESCRIPTION_IMAGE_GRID = False
ARCHIVE_VERSION = "0.3.2"
GOOGLE_API_KEY = "Replace with a valid Gemini API key in your GitHub repo secrets or locally"
GEMINI_MODEL = "gemini-3-flash-preview"  #  [m.name for m in genai.list_models()] to check other available models
GEMINI_CALLS = {"max_concurrency": 5, "max_retries": 8, "max_backoff": 70}  # avoid exceeding 5 RPM quota, 20 RPD https://ai.google.dev/gemini-api/docs/rate-limits
# Gemini usage metrics available at https://aistudio.google.com/usage?tab=rate-limit
